"""empty message

Revision ID: 50ebb5af4c52
Revises: d76f7b7ddade
Create Date: 2024-12-05 15:02:21.601034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ebb5af4c52'
down_revision = 'd76f7b7ddade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produkt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricetall', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pricetext', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produkt', schema=None) as batch_op:
        batch_op.drop_column('pricetext')
        batch_op.drop_column('pricetall')

    # ### end Alembic commands ###
